# syntax=docker/dockerfile:1

FROM caddy:alpine

COPY out /srv

RUN set -eu; \
	if [ ! -f /srv/redirects.caddy ]; then \
		printf '%s\n' '# Auto-generated by spa-crawler from observed redirects.' '# Include this file from your Caddy config.' '# rules_written: 0' '# skipped_query_sources: 0' > /srv/redirects.caddy; \
	fi

COPY Caddyfile /etc/caddy/Caddyfile

EXPOSE 8080
