name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref_type != 'tag' }}

jobs:
  check:
    permissions:
      contents: read
    uses: hu553in/common-things/.github/workflows/check-python.yml@main

  docker-crawler:
    permissions:
      contents: read
    uses: hu553in/common-things/.github/workflows/check-docker.yml@main
    with:
      file: ./Dockerfile.spa-crawler
      build: ${{ github.ref != 'refs/heads/main' }}

  docker-site:
    permissions:
      contents: read
    uses: hu553in/common-things/.github/workflows/check-docker.yml@main
    with:
      file: ./Dockerfile.spa

  publish:
    needs: [check, docker-crawler, docker-site]
    if: github.ref == 'refs/heads/main'
    uses: hu553in/common-things/.github/workflows/build-publish-attest-docker.yml@main
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    with:
      image: ghcr.io/${{ github.repository }}
      file: ./Dockerfile.spa-crawler
